apiVersion: v1
# objstore.yml: |-
#     type: s3
#     config:
#       bucket:
#       endpoint:
#       access_key:
#       secret_key:
#       insecure: true
kind: Secret
metadata:
    name: thanos-objstore
    namespace: monitoring
stringData:
    objstore.yml: ENC[AES256_GCM,data:DH7ECLyIxP9My7YGGz+R/Qn8tq3c3Qm6LcyJVAzkkUNtDxHGnCjZi//0VRMxF0vyAkAtolQoraj/6Eav2g4A5nYtCBxvLqjEEfrqwgE7LnN4QMUVM/NjnHah0ZjdPnij2wdUWCzffQyjn5K5yzmYJ/PIBOnm6O+UOB72fUUtGlbFRQWqO7ZNTVqrPO+l9bvDoKAV,iv:P4bENNUFmfX60vAn2l67WcRdkq72BSNs2DEkDcE2+Rw=,tag:wk1yGgnoB20tjqGEx2czTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1sv3k3xpc3r8glku67cew5cv787ly3zw4trx4dakduzvdus5st9xsc8apkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWFhLVjVvYm1xV1hEKzJa
            UGJHSmtxTFl2UDlWVTJ5a1RTQW9VZ0RmRUU0CjQ0TkkyNTZ5MkZWZTkxRHlDVE44
            eWlsT0FjbVg3dkg1RGJncWtuWEZLRzAKLS0tIGV5NVBING04dzB3NU1Ja0V0cHhw
            b3ZsTGJtSjNIRE5WOWxETFRULzM4aTAKvkp7cFtVh0Akf0sA6H/dPD01KS/gKhro
            R4VbZvSTsXJM/CHf5m7i+edYCmgmglht0dS8AzX/Zvl5SKuxCSf4fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-01-24T19:47:49Z"
    mac: ENC[AES256_GCM,data:xF/G1BrJAzPHsGVg3zfpfbMheHf0JRJAWYUYZJet3m9eaHHBnYcyVYRpz4gqRWDp/bxIrsl1c5fRt9885+TPRmw3bjUth2vuwLRmGUMwdZ+AsiyY5ItXCETJ7cX5/io5C4XYVsY4FQkbbHB8c/rZ3zcTzSDrsPa3DpfaGnQuEtU=,iv:tvF+ptu9QH4gJoH16P8FyujOyOfsdusuuhC33SujsPA=,tag:RbtsE7+v6fTYq0/6JpjIAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1

